#! python3
#
# processCOVIDData.py - Calculates the cumulative number of COVID deaths by state
#
# Scrapes and parses the COVID-19 data generated by the Johns Hopkins University @ https://github.com/CSSEGISandData/COVID-19.
# Processes the data for use in custom data analyses.

from pathlib import Path
import csv, pyperclip, sys
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys

#The total COVID deaths of each county in each state
countyStatesDeathToll = {}
#The population of each county in each state
countyStatesPopulation = {}
#The total COVID deaths on a state level
stateDeathToll = {}

#Use Google Chrome browser
driver = webdriver.Chrome(executable_path='C:\\Users\\wdpar\\python\\chromedriver.exe')

#Open the website
driver.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv')

#Select and copy all the data
actions = ActionChains(driver)
actions.key_down(Keys.CONTROL).send_keys('A').key_up(Keys.CONTROL).perform()
actions.key_down(Keys.CONTROL).send_keys('C').key_up(Keys.CONTROL).perform()

#Pull the data into a variable
data = pyperclip.paste()

#Close the browser window
driver.close()

#Set up the path where the raw data will go
covidDataPath = Path('F:/datasets/time_series_covid_19_deaths_US_johns_hopkins.csv')

#Open the new file to write the data to it
rawDataFile = open(covidDataPath, 'w')

#Write the data to the file
rawDataFile.write(data)

#Close the data file
rawDataFile.close()

#Read the first row of data (column titles)
with open(covidDataPath, newline='\n') as f:
    reader = csv.reader(f)
    header = next(reader)
    for rows in reader:
        county = rows[5]
        state = rows[6]
        population = rows[11]
        totalDeaths = rows[len(rows) - 1]
        countyState = county + ', ' + state
        if countyState not in countyStatesDeathToll.keys():
            countyStatesDeathToll.setdefault(countyState, [state, totalDeaths])
        if countyState not in countyStatesPopulation.keys():
            countyStatesPopulation.setdefault(countyState, [state, population])
        if state not in stateDeathToll.keys():
            stateDeathToll.setdefault(state, 0)

#Generate the state-level death toll by getting the cumulative sum of the counties therein
for keys, values in countyStatesDeathToll.items():
    for state in stateDeathToll.keys():
        if str(state) == str(values[0]):
            stateDeathToll[state] += int(values[1])

#Set up the path to the new output file
stateLevelCOVIDDeaths = Path('F:/datasets/stateLevelCOVIDDeaths.csv')

#Open the new file to write the data to it
newFile = open(stateLevelCOVIDDeaths, 'w')

#Write the column names of the output file
newFile.write('State,Total COVID-19 Deaths\n')

#Now write the data
for keys in stateDeathToll.keys():
    newFile.write(keys + ',' + str(stateDeathToll[keys]) + '\n')

#Close the file
newFile.close()

sys.exit()
