#! python3
#
# processCOVIDData.py - Calculates the cumulative number of COVID deaths by state
#
# Scrapes and parses the COVID-19 data generated by the Johns Hopkins University @ https://github.com/CSSEGISandData/COVID-19.
# Processes the data for use in custom data analyses.

from pathlib import Path
import csv, pyperclip, sys
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys

#------------------------------------ COVID Data Processing ---------------------------------------#

#The total COVID deaths of each county in each state
countyStatesDeathToll = {}
#The total COVID deaths on a state level
stateDeathToll = {}

#Use Google Chrome browser
driver = webdriver.Chrome(executable_path='C:\\Users\\wdpar\\python\\chromedriver.exe')

#Open the website
driver.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv')

#Select and copy all the data
actions = ActionChains(driver)
actions.key_down(Keys.CONTROL).send_keys('A').key_up(Keys.CONTROL).perform()
actions.key_down(Keys.CONTROL).send_keys('C').key_up(Keys.CONTROL).perform()

#Pull the data into a variable
data = pyperclip.paste()

#Close the browser window
driver.close()

#Set up the path where the raw COVID data will go
covidDataPath = Path('F:/datasets/time_series_covid_19_deaths_US_johns_hopkins.csv')

#Open the new file to write the data to it
rawDataFile = open(covidDataPath, 'w')

#Write the data to the file
rawDataFile.write(data)

#Close the data file
rawDataFile.close()

#Read the first row of data (column titles)
with open(covidDataPath, newline='\n') as f:
    reader = csv.reader(f)
    header = next(reader)
    for rows in reader:
        county = rows[5]
        state = rows[6]
        population = rows[11]
        totalDeaths = rows[len(rows) - 1]
        countyState = county + ', ' + state
        percentCountyDeaths = 0
        if int(population) != 0:
            percentCountyDeaths = (int(totalDeaths)/int(population)) * 100
        if countyState not in countyStatesDeathToll.keys():
            countyStatesDeathToll.setdefault(countyState, [county, state, totalDeaths, population, percentCountyDeaths])
        if state not in stateDeathToll.keys():
            #stateDeathToll will be in the format {state, [total deaths, population, percent dead]}
            stateDeathToll.setdefault(state, [0, 0, 0])

#Generate the state-level death toll by getting the cumulative sum of the counties therein
for keys, values in countyStatesDeathToll.items():
    for state, values2 in stateDeathToll.items():
        if str(state) == str(values[1]):
            values2[0] += int(values[2])
            values2[1] += int(values[3])


#Now get each state's percent deaths from COVID-19
for keys in stateDeathToll.keys():
    stateDeathToll[keys][2] = 0
    if stateDeathToll[keys][1] != 0:
        stateDeathToll[keys][2] = int((stateDeathToll[keys])[0]) / int((stateDeathToll[keys])[1]) * 100


#Set up the path to the new state-level output file
stateLevelCOVIDDeaths = Path('F:/datasets/stateLevelCOVIDDeaths.csv')

#Write to the output file
with open(stateLevelCOVIDDeaths, 'w') as f:
    writer = csv.writer(f, lineterminator='\n')

    #Write the column names
    f.write('State,Total COVID-19 Deaths,Population,Percent Dead from COVID-19\n')

    #Write the data
    for keys, values in stateDeathToll.items():
        dataEntry = [keys, values[0], values[1], values[2]]
        writer.writerow(dataEntry)

#Let's also get county-level statistics
countyLevelCOVIDDeaths = Path('F:/datasets/countyLevelCOVIDDeaths.csv')

#Write to the output file
with open(countyLevelCOVIDDeaths, 'w') as f:
    writer = csv.writer(f, lineterminator='\n')

    #Write the column names
    f.write('County,State,Total COVID-19 Deaths,Population,Percent Population Dead from COVID-19\n')

    #Write the data
    for keys, values in countyStatesDeathToll.items():
        dataEntry = [values[0], values[1], values[2], values[3], values[4]]
        writer.writerow(dataEntry)
